# Generated by Django 4.0.4 on 2022-05-28 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0003_stu_subject_course_detail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_subject',
            name='course_detail_file',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='stu_subject',
            name='course_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.course'),
        ),
        migrations.CreateModel(
            name='Teacher_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('image', models.ImageField(default='none', upload_to='img/')),
                ('details_updated', models.DateTimeField(auto_now_add=True)),
                ('subject_taught', models.ManyToManyField(to='Student.stu_subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='none', upload_to='img/')),
                ('details_updated', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=150)),
                ('admission_date', models.DateField()),
                ('previous_college', models.CharField(max_length=150)),
                ('course_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.modeluniversity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
