# Generated by Django 4.0.4 on 2022-05-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_stu_subject_course_detail_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='semester',
            field=models.CharField(choices=[('First Sem', 'First Semster'), ('Second Sem', 'Second Semester'), ('Third Sem', 'Third Semester'), ('Fourth Sem', 'Fourth Semester'), ('Fifth Sem', 'Fifth Semester'), ('Sixth Sem', 'Sixth Semester'), ('Seventh Sem', 'Seventh Semester'), ('Eighth Sem', 'Eighth Semester')], default=None, max_length=20),
        ),
    ]
