# Generated by Django 4.0.4 on 2022-05-31 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_student_details_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_subject',
            name='course_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.modeluniversity'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('assigned_data', models.FileField(upload_to='assignment/')),
                ('posting_date', models.DateField()),
                ('posting_time', models.TimeField()),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.teacher_details')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.stu_subject')),
            ],
        ),
    ]
