# Generated by Django 4.0.4 on 2022-05-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_stu_subject_course_related_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
