# Generated by Django 4.0.4 on 2022-06-01 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField()),
                ('submitted_time', models.TimeField()),
                ('submitted_data', models.FileField(upload_to='assignment/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.assignment')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.student_details')),
            ],
        ),
    ]
