# Generated by Django 4.0.4 on 2022-06-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_submitassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignment',
            name='edited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submitassignment',
            name='submitted_data',
            field=models.FileField(upload_to='assignmentsubmitted/'),
        ),
    ]
