# Generated by Django 4.0.4 on 2022-06-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_submitassignment_edited_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitAssignment',
        ),
    ]
