# Generated by Django 4.0.4 on 2022-06-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_submitassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitAssignment',
        ),
    ]
