# Generated by Django 4.0.4 on 2022-06-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_submitassignment_assignmentcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcheck',
            name='suggestion_for_wrong',
            field=models.TextField(default=None),
        ),
    ]
