# Generated by Django 4.0.4 on 2022-06-03 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_assignmentcheck_suggestion_for_wrong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submitassignment',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='AssignmentCheck',
        ),
        migrations.DeleteModel(
            name='SubmitAssignment',
        ),
    ]
