# Generated by Django 4.0.4 on 2022-06-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_correctanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
    ]
